# Generated by Django 5.0.6 on 2024-06-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TyF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuegosDeMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Autor', models.TextField()),
                ('Titulo', models.CharField(max_length=200)),
                ('Descripción', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoJuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Autor', models.TextField()),
                ('Titulo', models.CharField(max_length=200)),
                ('Descripción', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
