# Generated by Django 5.0.6 on 2024-06-26 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TyF', '0003_rename_autor_juegosdemesa_autor_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='juegosdemesa',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='juegosdemesa',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='juegosdemesa',
            name='id',
        ),
        migrations.RemoveField(
            model_name='juegosdemesa',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='videojuegos',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='videojuegos',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='videojuegos',
            name='id',
        ),
        migrations.RemoveField(
            model_name='videojuegos',
            name='titulo',
        ),
        migrations.AddField(
            model_name='juegosdemesa',
            name='duracion',
            field=models.CharField(default='30-60', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juegosdemesa',
            name='edad_recomendada',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juegosdemesa',
            name='numero_jugadores',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videojuegos',
            name='genero',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videojuegos',
            name='plataforma',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juegosdemesa',
            name='productobase_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TyF.productobase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videojuegos',
            name='productobase_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TyF.productobase'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_object_id', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TyF.categoria')),
                ('producto_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_object_id', models.PositiveIntegerField()),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TyF.etiqueta')),
                ('producto_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
