# Generated by Django 5.0.6 on 2024-06-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TyF', '0004_categoria_etiqueta_productobase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productobase',
            name='precio',
            field=models.CharField(max_length=10),
        ),
    ]
